### PR TITLE
Application date save bug

### LINKED ISSUE #205: FE/BE Refactor/Bug: User should be able to save a job application without selecting "Date Applied"
**Description**

When creating a new job application, the user is given the option to select “Not Yet Applied” from the **Application Status** dropdown.

However, if the user tries to save the application **without selecting a date in the "Date Applied" field**, the form will not submit — even though they have indicated they have not applied yet.

**SCREENSHOT**

Image

**Expected Behavior**

Users should be able to save a job application **without selecting a "Date Applied"** if the application status is set to **Not Yet Applied**. Requiring a date in this case is misleading and creates a blocker for users in early stages of their job search.

### PR DESCRIPTION
**Pull request by bevgreen**
### Type of Change
- [X] bug fix 🐛
- [X] refactor 🧑‍💻
- [X] testing 🧪

### Description
A user can now save a new job application with no date, if they select `not_yet_applied` as the status. I added two tests to the job application model to check validity. I also added an enum to the job application model. I did this because the back end only had numeric status codes. This was confusing because I had to go digging on the front end to see what these codes correlated to. I had to add the `attributes ... ` lines to the serializer because the front end is still expecting an integer as the JSON response. I changed status codes in tests from numbers to `:submitted` or `:offer` or whatever code made sense to put in the test. There were some `status: 0` lines of code I removed since 0 doesn't refer to any sort of status and was just confusing. Hopefully now the back end is more readable for someone just hopping in the codebase. 

### Share the reason(s) for this pull request
A user can now save a new application without a date if they haven't applied. 

### What questions do you have/what do you want feedback on?
Did I go overboard on this fix or was going through the trouble of making this more readable a good idea? 

### Related Tickets
closes #205 

### Added Test?
- [X] Yes 🫡
  - <!--- If yes, what type? Integration(FE), Unit/Model or Request/Controller Specs?-->
- Job application model spec

### Brakeman Results (REQUIRED):
<!--- Copy and paste your bm-report.md -->
# BRAKEMAN REPORT

| Application path                                                  | Rails version | Brakeman version | Started at                | Duration         |
|-------------------------------------------------------------------|---------------|------------------|---------------------------|------------------|
| /Users/beverlygreen/turing_work/4mod/capstone_project/tracker-crm | 7.1.5         | 7.0.2            | 2025-05-16 14:37:57 -0500 | 0.219734 seconds |

| Checks performed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| BasicAuth, BasicAuthTimingAttack, CSRFTokenForgeryCVE, ContentTag, CookieSerialization, CreateWith, CrossSiteScripting, DefaultRoutes, Deserialize, DetailedExceptions, DigestDoS, DivideByZero, DynamicFinders, EOLRails, EOLRuby, EscapeFunction, Evaluation, Execute, FileAccess, FileDisclosure, FilterSkipping, ForceSSL, ForgerySetting, HeaderDoS, I18nXSS, JRubyXML, JSONEncoding, JSONEntityEscape, JSONParsing, LinkTo, LinkToHref, MailTo, MassAssignment, MimeTypeDoS, ModelAttrAccessible, ModelAttributes, ModelSerialize, NestedAttributes, NestedAttributesBypass, NumberToCurrency, PageCachingCVE, Pathname, PermitAttributes, QuoteTableName, Ransack, Redirect, RegexDoS, Render, RenderDoS, RenderInline, ResponseSplitting, ReverseTabnabbing, RouteDoS, SQL, SQLCVEs, SSLVerify, SafeBufferManipulation, SanitizeConfigCve, SanitizeMethods, Secrets, SelectTag, SelectVulnerability, Send, SendFile, SessionManipulation, SessionSettings, SimpleFormat, SingleQuotes, SkipBeforeFilter, SprocketsPathTraversal, StripTags, SymbolDoS, SymbolDoSCVE, TemplateInjection, TranslateBug, UnsafeReflection, UnsafeReflectionMethods, UnscopedFind, ValidationRegex, VerbConfusion, WeakHash, WeakRSAKey, WithoutProtection, XMLDoS, YAMLParsing |

### SUMMARY

| Scanned/Reported  | Total |
|-------------------|-------|
| Controllers       | 8     |
| Models            | 8     |
| Templates         | 1     |
| Errors            | 0     |
| Security Warnings | 0 (0) |
<!--- Between these two comments -->

### Checklist:
<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [X] All tests (previous and new) pass 🥳
- [ ] This PR includes a Migration and I have notified the PM so they can run the migration after the PR is merged.
<!--- Delete any above that do not apply to this PR -->

### How to QA this change:
<!--- Outline the steps needed to locally verify the implemented changes are working as intended -->

### CODE REVIEW

**Review by jinman14 — APPROVED** [review]
Love me a good enum (mainly because I really learned it not too long ago, so I'm proud of myself too haha). 

Code looks good, I see you had to alter a few tests and seed data. Everything seems to pass. I see you had to alter all the old values and change them to the new enum limitations. All and all, nicely done.

File: spec/models/job_application_spec.rb [hunk 1]
```diff
@@ -30,7 +37,7 @@
       JobApplication.create!(
         position_title: "Jr. CTO",
         date_applied: "2024-10-31",
-        status: 1,
+        status: :submitted,
```
Comment (willfox0409) [inline spec/models/job_application_spec.rb:40]: Way better with semantic words here rather than arbitrary numbers!

File: app/models/job_application.rb [hunk 2]
```diff
@@ -3,9 +3,19 @@ class JobApplication < ApplicationRecord
   belongs_to :user
   belongs_to :contact, optional: true
   has_many :interview_questions
+  
+  enum status: {
```
Comment (willfox0409) [inline app/models/job_application.rb:7]: Yes! Love the explicit status declarations here, way more comprehensive

**Review by willfox0409 — APPROVED** [review]

File: app/models/job_application.rb (hunk 2 above)
Comment (willfox0409) [reply app/models/job_application.rb:7]: Whoa cool! I didn't realize the impact of this enum keyword, or the purpose of it. How cool to be able to map those integer values in the db to symbolic, expressive names in the code. Ya learn something new everyday!

**Review by ontruster74 — APPROVED** [review]
Good work on these changes. I'll be checking to see if there are any other user input fields that need this kind of fix on the BE as well.
